"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const electronAPI = {
    // ---- App ----
    getVersion: () => electron_1.ipcRenderer.invoke("app:getVersion"),
    getPlatform: () => electron_1.ipcRenderer.invoke("app:getPlatform"),
    minimizeWindow: () => electron_1.ipcRenderer.invoke("window:minimize"),
    toggleMaximizeWindow: () => electron_1.ipcRenderer.invoke("window:toggleMaximize"),
    closeWindow: () => electron_1.ipcRenderer.invoke("window:close"),
    isWindowMaximized: () => electron_1.ipcRenderer.invoke("window:isMaximized"),
    toggleFullscreenWindow: () => electron_1.ipcRenderer.invoke("window:toggleFullscreen"),
    isWindowFullscreen: () => electron_1.ipcRenderer.invoke("window:isFullscreen"),
    printHtml: (html, options) => electron_1.ipcRenderer.invoke("app:printHtml", html, options),
    listPrinters: () => electron_1.ipcRenderer.invoke("printers:list"),
    printReceipt: (html, options) => electron_1.ipcRenderer.invoke("printers:printReceipt", html, options),
    printTestReceipt: (options) => electron_1.ipcRenderer.invoke("printers:printTestReceipt", options),
    // ---- Auth ----
    login: (email, password) => electron_1.ipcRenderer.invoke("auth:login", email, password),
    logout: (userId, shiftId) => electron_1.ipcRenderer.invoke("auth:logout", userId, shiftId),
    // ---- Users ----
    listUsers: () => electron_1.ipcRenderer.invoke("users:list"),
    listUsersPaged: (query) => electron_1.ipcRenderer.invoke("users:listPaged", query),
    getUserById: (id) => electron_1.ipcRenderer.invoke("users:getById", id),
    getUserActivityById: (id) => electron_1.ipcRenderer.invoke("users:getActivityById", id),
    getUserShiftOperations: (shiftId) => electron_1.ipcRenderer.invoke("users:getShiftOperations", shiftId),
    createUser: (data) => electron_1.ipcRenderer.invoke("users:create", data),
    updateUser: (id, data) => electron_1.ipcRenderer.invoke("users:update", id, data),
    deleteUser: (id) => electron_1.ipcRenderer.invoke("users:delete", id),
    // ---- Categories ----
    listCategories: () => electron_1.ipcRenderer.invoke("categories:list"),
    getCategoryById: (id) => electron_1.ipcRenderer.invoke("categories:getById", id),
    createCategory: (data) => electron_1.ipcRenderer.invoke("categories:create", data),
    updateCategory: (id, data) => electron_1.ipcRenderer.invoke("categories:update", id, data),
    deleteCategory: (id) => electron_1.ipcRenderer.invoke("categories:delete", id),
    deleteAllCategories: () => electron_1.ipcRenderer.invoke("categories:deleteAll"),
    // ---- Products ----
    listProducts: (activeOnly) => electron_1.ipcRenderer.invoke("products:list", activeOnly),
    listProductsLite: (activeOnly) => electron_1.ipcRenderer.invoke("products:listLite", activeOnly),
    listProductsPaged: (query) => electron_1.ipcRenderer.invoke("products:listPaged", query),
    getProductById: (id) => electron_1.ipcRenderer.invoke("products:getById", id),
    getProductByBarcode: (barcode) => electron_1.ipcRenderer.invoke("products:getByBarcode", barcode),
    createProduct: (data) => electron_1.ipcRenderer.invoke("products:create", data),
    updateProduct: (id, data) => electron_1.ipcRenderer.invoke("products:update", id, data),
    deleteProduct: (id) => electron_1.ipcRenderer.invoke("products:delete", id),
    deleteAllProducts: () => electron_1.ipcRenderer.invoke("products:deleteAll"),
    // ---- Customers ----
    listCustomers: () => electron_1.ipcRenderer.invoke("customers:list"),
    listCustomersPaged: (query) => electron_1.ipcRenderer.invoke("customers:listPaged", query),
    getCustomerById: (id) => electron_1.ipcRenderer.invoke("customers:getById", id),
    createCustomer: (data) => electron_1.ipcRenderer.invoke("customers:create", data),
    updateCustomer: (id, data) => electron_1.ipcRenderer.invoke("customers:update", id, data),
    deleteCustomer: (id) => electron_1.ipcRenderer.invoke("customers:delete", id),
    deleteAllCustomers: () => electron_1.ipcRenderer.invoke("customers:deleteAll"),
    // ---- Suppliers ----
    listSuppliers: () => electron_1.ipcRenderer.invoke("suppliers:list"),
    listSuppliersPaged: (query) => electron_1.ipcRenderer.invoke("suppliers:listPaged", query),
    getSupplierById: (id) => electron_1.ipcRenderer.invoke("suppliers:getById", id),
    createSupplier: (data) => electron_1.ipcRenderer.invoke("suppliers:create", data),
    updateSupplier: (id, data) => electron_1.ipcRenderer.invoke("suppliers:update", id, data),
    deleteSupplier: (id) => electron_1.ipcRenderer.invoke("suppliers:delete", id),
    deleteAllSuppliers: () => electron_1.ipcRenderer.invoke("suppliers:deleteAll"),
    listSupplierOperations: (supplierId) => electron_1.ipcRenderer.invoke("suppliers:listOperations", supplierId),
    createSupplierOperation: (data) => electron_1.ipcRenderer.invoke("suppliers:createOperation", data),
    settleSupplierDebt: (data) => electron_1.ipcRenderer.invoke("suppliers:settleDebt", data),
    settleSupplierDebtAll: (supplierId, note) => electron_1.ipcRenderer.invoke("suppliers:settleDebtAll", supplierId, note),
    // ---- Sales ----
    listSales: (query) => electron_1.ipcRenderer.invoke("sales:list", query),
    listSalesPaged: (query) => electron_1.ipcRenderer.invoke("sales:listPaged", query),
    listSalesTimelinePaged: (query) => electron_1.ipcRenderer.invoke("sales:listTimelinePaged", query),
    getSaleById: (id) => electron_1.ipcRenderer.invoke("sales:getById", id),
    createSale: (data) => electron_1.ipcRenderer.invoke("sales:create", data),
    updateSale: (id, data) => electron_1.ipcRenderer.invoke("sales:update", id, data),
    updateSaleStatus: (id, status) => electron_1.ipcRenderer.invoke("sales:updateStatus", id, status),
    refundSale: (data) => electron_1.ipcRenderer.invoke("sales:refund", data),
    deleteSale: (id) => electron_1.ipcRenderer.invoke("sales:delete", id),
    deleteAllSales: () => electron_1.ipcRenderer.invoke("sales:deleteAll"),
    // ---- Returns ----
    listReturns: (query) => electron_1.ipcRenderer.invoke("returns:list", query),
    listReturnsPaged: (query) => electron_1.ipcRenderer.invoke("returns:listPaged", query),
    getReturnById: (id) => electron_1.ipcRenderer.invoke("returns:getById", id),
    createReturn: (data) => electron_1.ipcRenderer.invoke("returns:create", data),
    createReturnsBatch: (data) => electron_1.ipcRenderer.invoke("returns:createBatch", data),
    updateReturnStatus: (id, status) => electron_1.ipcRenderer.invoke("returns:updateStatus", id, status),
    deleteReturn: (id) => electron_1.ipcRenderer.invoke("returns:delete", id),
    deleteAllReturns: () => electron_1.ipcRenderer.invoke("returns:deleteAll"),
    // ---- Treasury ----
    getTreasurySummary: () => electron_1.ipcRenderer.invoke("treasury:getSummary"),
    listTreasuryOps: () => electron_1.ipcRenderer.invoke("treasury:listOps"),
    createTreasuryOp: (data) => electron_1.ipcRenderer.invoke("treasury:createOp", data),
    deleteTreasuryOp: (id) => electron_1.ipcRenderer.invoke("treasury:deleteOp", id),
    deleteAllTreasuryOps: () => electron_1.ipcRenderer.invoke("treasury:deleteAllOps"),
    // ---- Reports ----
    getReportsNetRevenue: (query) => electron_1.ipcRenderer.invoke("reports:getNetRevenue", query),
    getReportsSummary: (query) => electron_1.ipcRenderer.invoke("reports:getSummary", query),
    // ---- Settings ----
    getSettings: () => electron_1.ipcRenderer.invoke("settings:get"),
    updateSettings: (data) => electron_1.ipcRenderer.invoke("settings:update", data),
    resetData: (scope) => electron_1.ipcRenderer.invoke("settings:resetData", scope),
    resetOperations: () => electron_1.ipcRenderer.invoke("settings:resetOperations"),
    getAutoBackupStatus: () => electron_1.ipcRenderer.invoke("settings:getAutoBackupStatus"),
    createAutoBackup: (scope) => electron_1.ipcRenderer.invoke("settings:createAutoBackup", scope),
    createBackup: (scope) => electron_1.ipcRenderer.invoke("settings:createBackup", scope),
    restoreBackup: (scope) => electron_1.ipcRenderer.invoke("settings:restoreBackup", scope),
    // ---- Cloud Sync ----
    getCloudSyncSettings: () => electron_1.ipcRenderer.invoke("cloud:getSettings"),
    saveCloudSyncSettings: (data) => electron_1.ipcRenderer.invoke("cloud:saveSettings", data),
    syncNow: () => electron_1.ipcRenderer.invoke("cloud:syncNow"),
    testCloudConnection: (serverUrl, apiKey) => electron_1.ipcRenderer.invoke("cloud:testConnection", serverUrl, apiKey),
};
electron_1.contextBridge.exposeInMainWorld("electronAPI", electronAPI);
