"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hashPassword = exports.seedDatabase = exports.getDatabasePath = exports.closeDatabase = exports.getDb = exports.initDatabase = void 0;
var connection_1 = require("./connection");
Object.defineProperty(exports, "initDatabase", { enumerable: true, get: function () { return connection_1.initDatabase; } });
Object.defineProperty(exports, "getDb", { enumerable: true, get: function () { return connection_1.getDb; } });
Object.defineProperty(exports, "closeDatabase", { enumerable: true, get: function () { return connection_1.closeDatabase; } });
Object.defineProperty(exports, "getDatabasePath", { enumerable: true, get: function () { return connection_1.getDatabasePath; } });
var seed_1 = require("./seed");
Object.defineProperty(exports, "seedDatabase", { enumerable: true, get: function () { return seed_1.seedDatabase; } });
Object.defineProperty(exports, "hashPassword", { enumerable: true, get: function () { return seed_1.hashPassword; } });
